baseurl = "https://villakotabatu.netlify.app"
languageCode = "en-us"
paginate = "6"
summaryLength = "10"
theme = "parsa-hugo"
title = "Villa Kota Batu - Info Tarif & Penginapan"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true



[[menu.main]]
hasChildren = ""
name = "Homepage"
url = ""
weight = "1"
[[menu.main]]
name = "About"
url = "about"
weight = 2
[[menu.main]]
name = "Contact"
url = "contact"
weight = 3
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
address = "Jl. Kampung satelite Batu Malang"
author = "Villa Kota Batu"
author_image = "images/banner-img.png"
bio = "Informasi Harga sewa Villa di Batu malang Fasilitas Kolam Renang View Pemandangan Terbaik"
contact_form_action = "#"
copyright = "Copyright &copy; 2020"
description = "Informasi Harga sewa Villa Dekat Wisata di Batu malang Fasilitas Kolam Renang Dan Non Kolam Renang Dengan Harga Dan View Pemandangan Terbaik"
email = "exmaple@ymail.com"
google_analitycs_id = "Your ID"
home = "Home"
layout = "2"
logo = "images/logo.png"
mobile = "+90 000 333 22"
preloader = false
search = true
[params.cookies]
enable = true
expire_days = 2
[params.instafeed]
access_token = "IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn"
enable = true
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.social]]
icon = "ti-facebook"
url = "#"
[[params.social]]
icon = "ti-twitter-alt"
url = "#"
[[params.social]]
icon = "ti-linkedin"
url = "#"
[[params.social]]
icon = "ti-github"
url = "#"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
  
[permalinks]
  posts = "/:year/:month/:title/"
